spring.application.name=DOSW-ParcialT2

# Configuracion de PostgreSQL
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/Parcial2DB
spring.datasource.username=camilo
spring.datasource.password=camilo
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update